version = 1

D[[analyzers]]
name = "test-coverage"
enabled = true
  [analyzers.meta]
  coverage_paths = ["coverage.xml"]
  coverage_tool = "pytest"

[[analyzers]]
name = "python"
enabled = true
  [analyzers.meta]
  runtime_version = "3.11.x" 
  test_patterns = ["backend/tests/**/"]

[[analyzers]]
name = "javascript"
enabled = true
  [analyzers.meta]
  plugins = ["vue"]
  node_version = "18.x.x"
  environment = ["cypress", "nodejs"]
  test_patterns = ["frontend/tests/*"]

[[transformers]]
name = "black"

[[transformers]]
name = "isort"

[[transformers]]
name = "ruff"

[[transformers]]
name = "prettier"
